### ISSUE TITLE
Can bigmap be stable?

### ISSUE THREAD

**Issue by MCLYang** [aviate-labs/bimap.mo#5]
did not try yet but BiMap stable? if not how to implement in 
preupgrade() and postupgrade()?

**Comment by q-uint** [comment]
`BiMap` is not stable by default.
You should be able to use the same approach as you would with a normal `HashMap`.
i.e. use `entries<(L, R)>()` and `fromIter<L, R>(...)` to convert to/from a stable Array `[(L, R)]`.

---

https://github.com/aviate-labs/bimap.mo/blob/1eeb692d98321946bf2e981141e27b651b1e122a/src/BiMap.mo#L105-L108
https://github.com/aviate-labs/bimap.mo/blob/1eeb692d98321946bf2e981141e27b651b1e122a/src/BiMap.mo#L234-L245

**Comment by MCLYang** [comment]
Got it. I resolved it by the way to use Hashmap.
BTW, really appreciate the implementation of this. The Bimap data structure release my headache. 

Any way I can donate or sponsor for this project?
